const { Router } = require('express')
const Orders = require('./orders/orders')
const Login = require('./login/login')
const Orderparams = require('./orderparams/orderparams')
const Categories = require('./categories/categories')
const SubCategories = require('./sub_categories/sub_category')
const NewSubCategories = require('./new_sub_category/new_sub_category')
const Menu = require('./products/products')
const NewMenu = require('./products/products')

const router = new Router()
router
    .post('/login', Login.POST)
    .get('/orders', Orders.GET)
    .post('/orders', Orders.POST)
    .get('/orders/:id', Orderparams.GET)
    .get('/categories', Categories.GET)
    .post('/categories', Categories.POST)
    .delete('/categories', Categories.DELETE)
    .post('/sub_categories', SubCategories.POST)
    .delete('/del_sub_categories', SubCategories.DELETE)
    .get('/new_sub_categories', NewSubCategories.GET)
    .post('/new_sub_categories', NewSubCategories.POST)
    .get('/sub_categories/:id', SubCategories.GET)
    .get('/products', Menu.GET)
    .post('/menu', Menu.POST)
    .post('/new_menu', NewMenu.POST)
    .get('/time', (req, res) => {
        res.send(moment().format('l'))
    })

module.exports = router